version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks:
      - task-network-demo
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
    env_file:
      - .env

  task-listener:
    image: task-demo:latest
    container_name: task-listener
    networks:
      - task-network-demo
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
    env_file:
      - .env

networks:
  task-network:
    driver: bridge
